#!/bin/bash
if [[ "$1" != "" ]]; then
        mkdir $1
        cd $1
        home set 2>/dev/null
        ln -s /usr/share/seclists/Passwords/Leaked-Databases/rockyou.txt rockyou.txt
        ln -s /opt/Windows windows
        touch foothold.txt
        touch privesc.txt
        touch creds.txt
        touch hashes.txt
else
        echo "USAGE: $0 machine_name"
fi
